//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace NewsGatorSyscPlugin.LocationService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LocationWebServiceSoap", Namespace="http://services.newsgator.com/svc/Location.asmx")]
    public partial class LocationWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private NGImpersonate nGImpersonateValueField;
        
        private NGAPIToken nGAPITokenValueField;
        
        private System.Threading.SendOrPostCallback GetLocationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnreadCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSubscriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveSubscriptionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LocationWebService() {
            this.Url = global::NewsGatorSyscPlugin.Properties.Settings.Default.NewsGatorSyscPlugin_LocationSevice_LocationWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public NGImpersonate NGImpersonateValue {
            get {
                return this.nGImpersonateValueField;
            }
            set {
                this.nGImpersonateValueField = value;
            }
        }
        
        public NGAPIToken NGAPITokenValue {
            get {
                return this.nGAPITokenValueField;
            }
            set {
                this.nGAPITokenValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLocationsCompletedEventHandler GetLocationsCompleted;
        
        /// <remarks/>
        public event CreateLocationCompletedEventHandler CreateLocationCompleted;
        
        /// <remarks/>
        public event DeleteLocationCompletedEventHandler DeleteLocationCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event GetUnreadCountCompletedEventHandler GetUnreadCountCompleted;
        
        /// <remarks/>
        public event AddSubscriptionCompletedEventHandler AddSubscriptionCompleted;
        
        /// <remarks/>
        public event RemoveSubscriptionCompletedEventHandler RemoveSubscriptionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGAPITokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGImpersonateValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.newsgator.com/svc/Location.asmx/GetLocations", RequestNamespace="http://services.newsgator.com/svc/Location.asmx", ResponseNamespace="http://services.newsgator.com/svc/Location.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Location[] GetLocations() {
            object[] results = this.Invoke("GetLocations", new object[0]);
            return ((Location[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLocationsAsync() {
            this.GetLocationsAsync(null);
        }
        
        /// <remarks/>
        public void GetLocationsAsync(object userState) {
            if ((this.GetLocationsOperationCompleted == null)) {
                this.GetLocationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLocationsOperationCompleted);
            }
            this.InvokeAsync("GetLocations", new object[0], this.GetLocationsOperationCompleted, userState);
        }
        
        private void OnGetLocationsOperationCompleted(object arg) {
            if ((this.GetLocationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLocationsCompleted(this, new GetLocationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGAPITokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGImpersonateValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.newsgator.com/svc/Location.asmx/CreateLocation", RequestNamespace="http://services.newsgator.com/svc/Location.asmx", ResponseNamespace="http://services.newsgator.com/svc/Location.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateLocation(string name, bool autoAddSubs) {
            object[] results = this.Invoke("CreateLocation", new object[] {
                        name,
                        autoAddSubs});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateLocationAsync(string name, bool autoAddSubs) {
            this.CreateLocationAsync(name, autoAddSubs, null);
        }
        
        /// <remarks/>
        public void CreateLocationAsync(string name, bool autoAddSubs, object userState) {
            if ((this.CreateLocationOperationCompleted == null)) {
                this.CreateLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateLocationOperationCompleted);
            }
            this.InvokeAsync("CreateLocation", new object[] {
                        name,
                        autoAddSubs}, this.CreateLocationOperationCompleted, userState);
        }
        
        private void OnCreateLocationOperationCompleted(object arg) {
            if ((this.CreateLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateLocationCompleted(this, new CreateLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGAPITokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGImpersonateValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.newsgator.com/svc/Location.asmx/DeleteLocation", RequestNamespace="http://services.newsgator.com/svc/Location.asmx", ResponseNamespace="http://services.newsgator.com/svc/Location.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteLocation(int id) {
            this.Invoke("DeleteLocation", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void DeleteLocationAsync(int id) {
            this.DeleteLocationAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteLocationAsync(int id, object userState) {
            if ((this.DeleteLocationOperationCompleted == null)) {
                this.DeleteLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteLocationOperationCompleted);
            }
            this.InvokeAsync("DeleteLocation", new object[] {
                        id}, this.DeleteLocationOperationCompleted, userState);
        }
        
        private void OnDeleteLocationOperationCompleted(object arg) {
            if ((this.DeleteLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteLocationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGAPITokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGImpersonateValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.newsgator.com/svc/Location.asmx/Update", RequestNamespace="http://services.newsgator.com/svc/Location.asmx", ResponseNamespace="http://services.newsgator.com/svc/Location.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(Location location) {
            this.Invoke("Update", new object[] {
                        location});
        }
        
        /// <remarks/>
        public void UpdateAsync(Location location) {
            this.UpdateAsync(location, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(Location location, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        location}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGAPITokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGImpersonateValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.newsgator.com/svc/Location.asmx/GetUnreadCount", RequestNamespace="http://services.newsgator.com/svc/Location.asmx", ResponseNamespace="http://services.newsgator.com/svc/Location.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetUnreadCount(string name) {
            object[] results = this.Invoke("GetUnreadCount", new object[] {
                        name});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetUnreadCountAsync(string name) {
            this.GetUnreadCountAsync(name, null);
        }
        
        /// <remarks/>
        public void GetUnreadCountAsync(string name, object userState) {
            if ((this.GetUnreadCountOperationCompleted == null)) {
                this.GetUnreadCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnreadCountOperationCompleted);
            }
            this.InvokeAsync("GetUnreadCount", new object[] {
                        name}, this.GetUnreadCountOperationCompleted, userState);
        }
        
        private void OnGetUnreadCountOperationCompleted(object arg) {
            if ((this.GetUnreadCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnreadCountCompleted(this, new GetUnreadCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGAPITokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGImpersonateValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.newsgator.com/svc/Location.asmx/AddSubscription", RequestNamespace="http://services.newsgator.com/svc/Location.asmx", ResponseNamespace="http://services.newsgator.com/svc/Location.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddSubscription(int locId, int feedId) {
            this.Invoke("AddSubscription", new object[] {
                        locId,
                        feedId});
        }
        
        /// <remarks/>
        public void AddSubscriptionAsync(int locId, int feedId) {
            this.AddSubscriptionAsync(locId, feedId, null);
        }
        
        /// <remarks/>
        public void AddSubscriptionAsync(int locId, int feedId, object userState) {
            if ((this.AddSubscriptionOperationCompleted == null)) {
                this.AddSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSubscriptionOperationCompleted);
            }
            this.InvokeAsync("AddSubscription", new object[] {
                        locId,
                        feedId}, this.AddSubscriptionOperationCompleted, userState);
        }
        
        private void OnAddSubscriptionOperationCompleted(object arg) {
            if ((this.AddSubscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSubscriptionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGAPITokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("NGImpersonateValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.newsgator.com/svc/Location.asmx/RemoveSubscription", RequestNamespace="http://services.newsgator.com/svc/Location.asmx", ResponseNamespace="http://services.newsgator.com/svc/Location.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveSubscription(int locId, int feedId) {
            this.Invoke("RemoveSubscription", new object[] {
                        locId,
                        feedId});
        }
        
        /// <remarks/>
        public void RemoveSubscriptionAsync(int locId, int feedId) {
            this.RemoveSubscriptionAsync(locId, feedId, null);
        }
        
        /// <remarks/>
        public void RemoveSubscriptionAsync(int locId, int feedId, object userState) {
            if ((this.RemoveSubscriptionOperationCompleted == null)) {
                this.RemoveSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveSubscriptionOperationCompleted);
            }
            this.InvokeAsync("RemoveSubscription", new object[] {
                        locId,
                        feedId}, this.RemoveSubscriptionOperationCompleted, userState);
        }
        
        private void OnRemoveSubscriptionOperationCompleted(object arg) {
            if ((this.RemoveSubscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveSubscriptionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.newsgator.com/svc/Location.asmx")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://services.newsgator.com/svc/Location.asmx", IsNullable=false)]
    public partial class NGAPIToken : System.Web.Services.Protocols.SoapHeader {
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.newsgator.com/svc/Location.asmx")]
    public partial class Location {
        
        private int idField;
        
        private string nameField;
        
        private bool contentOnlineField;
        
        private bool autoAddSubsField;
        
        private bool isPublicField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool contentOnline {
            get {
                return this.contentOnlineField;
            }
            set {
                this.contentOnlineField = value;
            }
        }
        
        /// <remarks/>
        public bool autoAddSubs {
            get {
                return this.autoAddSubsField;
            }
            set {
                this.autoAddSubsField = value;
            }
        }
        
        /// <remarks/>
        public bool isPublic {
            get {
                return this.isPublicField;
            }
            set {
                this.isPublicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.newsgator.com/ngws/Impersonate")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://services.newsgator.com/ngws/Impersonate", IsNullable=false)]
    public partial class NGImpersonate : System.Web.Services.Protocols.SoapHeader {
        
        private string impersonateUserField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string ImpersonateUser {
            get {
                return this.impersonateUserField;
            }
            set {
                this.impersonateUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetLocationsCompletedEventHandler(object sender, GetLocationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLocationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLocationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Location[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Location[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void CreateLocationCompletedEventHandler(object sender, CreateLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void DeleteLocationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void UpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetUnreadCountCompletedEventHandler(object sender, GetUnreadCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnreadCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnreadCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void AddSubscriptionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void RemoveSubscriptionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591